import MarketingLayout from '@/Layouts/MarketingLayout';
import { Head } from '@inertiajs/react';

const sections = [
    ['Subscriptions', 'Access is granted per student and per subscribed subject while the subscription is active or in trial.'],
    ['Course access', 'Expired, cancelled, blocked or past-due subscriptions can restrict access while preserving historical records.'],
    ['Acceptable use', 'Accounts should not be shared outside the registered family or used to distribute protected lesson content.'],
    ['Certificates', 'Certificates may be verified through a public verification code generated by the platform.'],
];

export default function Terms() {
    return (
        <MarketingLayout>
            <Head title="Terms" />
            <section className="bg-white py-16">
                <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
                    <h1 className="text-4xl font-semibold text-slate-950">Terms of Service</h1>
                    <p className="mt-4 leading-7 text-slate-600">
                        These demo terms describe the expected platform rules for parents, students and staff.
                    </p>
                    <div className="mt-8 space-y-5">
                        {sections.map(([title, body]) => (
                            <section key={title} className="rounded-lg border border-slate-200 p-5">
                                <h2 className="font-semibold text-slate-900">{title}</h2>
                                <p className="mt-2 text-sm leading-6 text-slate-600">{body}</p>
                            </section>
                        ))}
                    </div>
                </div>
            </section>
        </MarketingLayout>
    );
}
